server:
  port: 5001
#开发环境
spring:
  datasource:
    url: jdbc:postgresql://43.137.43.142:5432/postgres?useUnicode=true&&characterEncoding=utf-8&useSSL=false
    username: root
    password: 656803
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
tarurl: 43.137.43.142:5001
isserver: false
key: spike