server:
  port: 8080
  address: localhost
  servlet:
    context-path: /spike
spring:
  application:
    name: Security_spike
  security:
    user:
      name: spike
      password: 656803
      roles: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxx:3306/cloud_project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: xx
    password: xxx
logging:
  level:
    com.spike.Mapper: trace