server:
  port: 8080
  address: localhost
  servlet:
    context-path: /spike
spring:
  profiles:
    active: dev
  application:
    name: spike_Main_service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka